//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailPOS.RetailPOSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductCategoryDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Category")]
    [System.SerializableAttribute()]
    public partial class ProductCategoryDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.StatusDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.ProductStatusDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.CustomerStatusDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.ProductDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.StaffDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.CustomerDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.AddressDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.CustomerTypeDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.MeasureUnitDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.CountryDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.TownCityDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.StreetDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.PostCodeDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.ShopSettingDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.WasteManagementDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.PromotionalOfferDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.ProductCategoryDTO))]
    public partial class BaseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        "")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.ProductStatusDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RetailPOS.RetailPOSService.CustomerStatusDTO))]
    public partial class StatusDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductStatusDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Product")]
    [System.SerializableAttribute()]
    public partial class ProductStatusDTO : RetailPOS.RetailPOSService.StatusDTO {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerStatusDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Customer")]
    [System.SerializableAttribute()]
    public partial class CustomerStatusDTO : RetailPOS.RetailPOSService.StatusDTO {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Product")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> Category_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> Has_WarrantyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PurchasePriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Retail_PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Status_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Tax_RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Wholesale_PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BarCode {
            get {
                return this.BarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarCodeField, value) != true)) {
                    this.BarCodeField = value;
                    this.RaisePropertyChanged("BarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Category_Id {
            get {
                return this.Category_IdField;
            }
            set {
                if ((this.Category_IdField.Equals(value) != true)) {
                    this.Category_IdField = value;
                    this.RaisePropertyChanged("Category_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Has_Warranty {
            get {
                return this.Has_WarrantyField;
            }
            set {
                if ((this.Has_WarrantyField.Equals(value) != true)) {
                    this.Has_WarrantyField = value;
                    this.RaisePropertyChanged("Has_Warranty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image_Path {
            get {
                return this.Image_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.Image_PathField, value) != true)) {
                    this.Image_PathField = value;
                    this.RaisePropertyChanged("Image_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PurchasePrice {
            get {
                return this.PurchasePriceField;
            }
            set {
                if ((this.PurchasePriceField.Equals(value) != true)) {
                    this.PurchasePriceField = value;
                    this.RaisePropertyChanged("PurchasePrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Retail_Price {
            get {
                return this.Retail_PriceField;
            }
            set {
                if ((this.Retail_PriceField.Equals(value) != true)) {
                    this.Retail_PriceField = value;
                    this.RaisePropertyChanged("Retail_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_Id {
            get {
                return this.Status_IdField;
            }
            set {
                if ((this.Status_IdField.Equals(value) != true)) {
                    this.Status_IdField = value;
                    this.RaisePropertyChanged("Status_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Tax_Rate {
            get {
                return this.Tax_RateField;
            }
            set {
                if ((this.Tax_RateField.Equals(value) != true)) {
                    this.Tax_RateField = value;
                    this.RaisePropertyChanged("Tax_Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Wholesale_Price {
            get {
                return this.Wholesale_PriceField;
            }
            set {
                if ((this.Wholesale_PriceField.Equals(value) != true)) {
                    this.Wholesale_PriceField = value;
                    this.RaisePropertyChanged("Wholesale_Price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StaffDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".User")]
    [System.SerializableAttribute()]
    public partial class StaffDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long Address_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Department_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Designation_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Hire_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenId_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OpenId_Server_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Security_Group_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Status_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Address_Id {
            get {
                return this.Address_IdField;
            }
            set {
                if ((this.Address_IdField.Equals(value) != true)) {
                    this.Address_IdField = value;
                    this.RaisePropertyChanged("Address_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Department_Id {
            get {
                return this.Department_IdField;
            }
            set {
                if ((this.Department_IdField.Equals(value) != true)) {
                    this.Department_IdField = value;
                    this.RaisePropertyChanged("Department_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Designation_Id {
            get {
                return this.Designation_IdField;
            }
            set {
                if ((this.Designation_IdField.Equals(value) != true)) {
                    this.Designation_IdField = value;
                    this.RaisePropertyChanged("Designation_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hire_Date {
            get {
                return this.Hire_DateField;
            }
            set {
                if ((this.Hire_DateField.Equals(value) != true)) {
                    this.Hire_DateField = value;
                    this.RaisePropertyChanged("Hire_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image_Path {
            get {
                return this.Image_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.Image_PathField, value) != true)) {
                    this.Image_PathField = value;
                    this.RaisePropertyChanged("Image_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpenId_Id {
            get {
                return this.OpenId_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenId_IdField, value) != true)) {
                    this.OpenId_IdField = value;
                    this.RaisePropertyChanged("OpenId_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OpenId_Server_Id {
            get {
                return this.OpenId_Server_IdField;
            }
            set {
                if ((this.OpenId_Server_IdField.Equals(value) != true)) {
                    this.OpenId_Server_IdField = value;
                    this.RaisePropertyChanged("OpenId_Server_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Security_Group_Id {
            get {
                return this.Security_Group_IdField;
            }
            set {
                if ((this.Security_Group_IdField.Equals(value) != true)) {
                    this.Security_Group_IdField = value;
                    this.RaisePropertyChanged("Security_Group_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_Id {
            get {
                return this.Status_IdField;
            }
            set {
                if ((this.Status_IdField.Equals(value) != true)) {
                    this.Status_IdField = value;
                    this.RaisePropertyChanged("Status_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Customer")]
    [System.SerializableAttribute()]
    public partial class CustomerDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RetailPOS.RetailPOSService.AddressDTO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> Address_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Credit_LimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Image_PathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenId_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> OpenId_Server_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Payment_PeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Status_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> Type_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal balanceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RetailPOS.RetailPOSService.AddressDTO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Address_Id {
            get {
                return this.Address_IdField;
            }
            set {
                if ((this.Address_IdField.Equals(value) != true)) {
                    this.Address_IdField = value;
                    this.RaisePropertyChanged("Address_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Credit_Limit {
            get {
                return this.Credit_LimitField;
            }
            set {
                if ((this.Credit_LimitField.Equals(value) != true)) {
                    this.Credit_LimitField = value;
                    this.RaisePropertyChanged("Credit_Limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_Name {
            get {
                return this.First_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_NameField, value) != true)) {
                    this.First_NameField = value;
                    this.RaisePropertyChanged("First_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image_Path {
            get {
                return this.Image_PathField;
            }
            set {
                if ((object.ReferenceEquals(this.Image_PathField, value) != true)) {
                    this.Image_PathField = value;
                    this.RaisePropertyChanged("Image_Path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_Name {
            get {
                return this.Last_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_NameField, value) != true)) {
                    this.Last_NameField = value;
                    this.RaisePropertyChanged("Last_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpenId_Id {
            get {
                return this.OpenId_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenId_IdField, value) != true)) {
                    this.OpenId_IdField = value;
                    this.RaisePropertyChanged("OpenId_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> OpenId_Server_Id {
            get {
                return this.OpenId_Server_IdField;
            }
            set {
                if ((this.OpenId_Server_IdField.Equals(value) != true)) {
                    this.OpenId_Server_IdField = value;
                    this.RaisePropertyChanged("OpenId_Server_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payment_Period {
            get {
                return this.Payment_PeriodField;
            }
            set {
                if ((this.Payment_PeriodField.Equals(value) != true)) {
                    this.Payment_PeriodField = value;
                    this.RaisePropertyChanged("Payment_Period");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status_Id {
            get {
                return this.Status_IdField;
            }
            set {
                if ((this.Status_IdField.Equals(value) != true)) {
                    this.Status_IdField = value;
                    this.RaisePropertyChanged("Status_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Type_Id {
            get {
                return this.Type_IdField;
            }
            set {
                if ((this.Type_IdField.Equals(value) != true)) {
                    this.Type_IdField = value;
                    this.RaisePropertyChanged("Type_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal balance {
            get {
                return this.balanceField;
            }
            set {
                if ((this.balanceField.Equals(value) != true)) {
                    this.balanceField = value;
                    this.RaisePropertyChanged("balance");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Master")]
    [System.SerializableAttribute()]
    public partial class AddressDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Building_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> Country_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string House_NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> Locality_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PostCode_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Street_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> Town_City_IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building_name {
            get {
                return this.Building_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Building_nameField, value) != true)) {
                    this.Building_nameField = value;
                    this.RaisePropertyChanged("Building_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Country_Id {
            get {
                return this.Country_IdField;
            }
            set {
                if ((this.Country_IdField.Equals(value) != true)) {
                    this.Country_IdField = value;
                    this.RaisePropertyChanged("Country_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string House_No {
            get {
                return this.House_NoField;
            }
            set {
                if ((object.ReferenceEquals(this.House_NoField, value) != true)) {
                    this.House_NoField = value;
                    this.RaisePropertyChanged("House_No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Locality_Id {
            get {
                return this.Locality_IdField;
            }
            set {
                if ((this.Locality_IdField.Equals(value) != true)) {
                    this.Locality_IdField = value;
                    this.RaisePropertyChanged("Locality_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostCode_Id {
            get {
                return this.PostCode_IdField;
            }
            set {
                if ((this.PostCode_IdField.Equals(value) != true)) {
                    this.PostCode_IdField = value;
                    this.RaisePropertyChanged("PostCode_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Street_Id {
            get {
                return this.Street_IdField;
            }
            set {
                if ((this.Street_IdField.Equals(value) != true)) {
                    this.Street_IdField = value;
                    this.RaisePropertyChanged("Street_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Town_City_Id {
            get {
                return this.Town_City_IdField;
            }
            set {
                if ((this.Town_City_IdField.Equals(value) != true)) {
                    this.Town_City_IdField = value;
                    this.RaisePropertyChanged("Town_City_Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerTypeDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Customer")]
    [System.SerializableAttribute()]
    public partial class CustomerTypeDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MeasureUnitDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Master")]
    [System.SerializableAttribute()]
    public partial class MeasureUnitDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Master")]
    [System.SerializableAttribute()]
    public partial class CountryDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TownCityDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Master")]
    [System.SerializableAttribute()]
    public partial class TownCityDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Town_City1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int countryIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town_City1 {
            get {
                return this.Town_City1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Town_City1Field, value) != true)) {
                    this.Town_City1Field = value;
                    this.RaisePropertyChanged("Town_City1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int countryID {
            get {
                return this.countryIDField;
            }
            set {
                if ((this.countryIDField.Equals(value) != true)) {
                    this.countryIDField = value;
                    this.RaisePropertyChanged("countryID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StreetDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Master")]
    [System.SerializableAttribute()]
    public partial class StreetDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street1 {
            get {
                return this.Street1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street1Field, value) != true)) {
                    this.Street1Field = value;
                    this.RaisePropertyChanged("Street1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostCodeDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Master")]
    [System.SerializableAttribute()]
    public partial class PostCodeDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short TownCityIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode1 {
            get {
                return this.PostCode1Field;
            }
            set {
                if ((object.ReferenceEquals(this.PostCode1Field, value) != true)) {
                    this.PostCode1Field = value;
                    this.RaisePropertyChanged("PostCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TownCityId {
            get {
                return this.TownCityIdField;
            }
            set {
                if ((this.TownCityIdField.Equals(value) != true)) {
                    this.TownCityIdField = value;
                    this.RaisePropertyChanged("TownCityId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShopSettingDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Settings")]
    [System.SerializableAttribute()]
    public partial class ShopSettingDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RetailPOS.RetailPOSService.AddressDTO AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> Address_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Tax_rateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RetailPOS.RetailPOSService.AddressDTO Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Address_Id {
            get {
                return this.Address_IdField;
            }
            set {
                if ((this.Address_IdField.Equals(value) != true)) {
                    this.Address_IdField = value;
                    this.RaisePropertyChanged("Address_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Tax_rate {
            get {
                return this.Tax_rateField;
            }
            set {
                if ((this.Tax_rateField.Equals(value) != true)) {
                    this.Tax_rateField = value;
                    this.RaisePropertyChanged("Tax_rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WasteManagementDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Settings")]
    [System.SerializableAttribute()]
    public partial class WasteManagementDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PromotionalOfferDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".PromotionalOffer")]
    [System.SerializableAttribute()]
    public partial class PromotionalOfferDTO : RetailPOS.RetailPOSService.BaseDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime End_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RetailPOS.RetailPOSService.MeasureUnitDTO Measure_UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RetailPOS.RetailPOSService.MeasureUnitDTO Measure_Unit1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfferQuantityWithUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Offer_PercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> Offer_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> Oqty_MuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Pqty_MuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurchaseQuantityWithUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Purchase_QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Start_DateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateDuration {
            get {
                return this.DateDurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDurationField, value) != true)) {
                    this.DateDurationField = value;
                    this.RaisePropertyChanged("DateDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End_Date {
            get {
                return this.End_DateField;
            }
            set {
                if ((this.End_DateField.Equals(value) != true)) {
                    this.End_DateField = value;
                    this.RaisePropertyChanged("End_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RetailPOS.RetailPOSService.MeasureUnitDTO Measure_Unit {
            get {
                return this.Measure_UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.Measure_UnitField, value) != true)) {
                    this.Measure_UnitField = value;
                    this.RaisePropertyChanged("Measure_Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RetailPOS.RetailPOSService.MeasureUnitDTO Measure_Unit1 {
            get {
                return this.Measure_Unit1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Measure_Unit1Field, value) != true)) {
                    this.Measure_Unit1Field = value;
                    this.RaisePropertyChanged("Measure_Unit1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfferQuantityWithUnit {
            get {
                return this.OfferQuantityWithUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferQuantityWithUnitField, value) != true)) {
                    this.OfferQuantityWithUnitField = value;
                    this.RaisePropertyChanged("OfferQuantityWithUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Offer_Percentage {
            get {
                return this.Offer_PercentageField;
            }
            set {
                if ((this.Offer_PercentageField.Equals(value) != true)) {
                    this.Offer_PercentageField = value;
                    this.RaisePropertyChanged("Offer_Percentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Offer_Quantity {
            get {
                return this.Offer_QuantityField;
            }
            set {
                if ((this.Offer_QuantityField.Equals(value) != true)) {
                    this.Offer_QuantityField = value;
                    this.RaisePropertyChanged("Offer_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Oqty_Mu {
            get {
                return this.Oqty_MuField;
            }
            set {
                if ((this.Oqty_MuField.Equals(value) != true)) {
                    this.Oqty_MuField = value;
                    this.RaisePropertyChanged("Oqty_Mu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pqty_Mu {
            get {
                return this.Pqty_MuField;
            }
            set {
                if ((this.Pqty_MuField.Equals(value) != true)) {
                    this.Pqty_MuField = value;
                    this.RaisePropertyChanged("Pqty_Mu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurchaseQuantityWithUnit {
            get {
                return this.PurchaseQuantityWithUnitField;
            }
            set {
                if ((object.ReferenceEquals(this.PurchaseQuantityWithUnitField, value) != true)) {
                    this.PurchaseQuantityWithUnitField = value;
                    this.RaisePropertyChanged("PurchaseQuantityWithUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Purchase_Quantity {
            get {
                return this.Purchase_QuantityField;
            }
            set {
                if ((this.Purchase_QuantityField.Equals(value) != true)) {
                    this.Purchase_QuantityField = value;
                    this.RaisePropertyChanged("Purchase_Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start_Date {
            get {
                return this.Start_DateField;
            }
            set {
                if ((this.Start_DateField.Equals(value) != true)) {
                    this.Start_DateField = value;
                    this.RaisePropertyChanged("Start_Date");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalityDTO", Namespace="http://schemas.datacontract.org/2004/07/RetailPOS.CommonLayer.DataTransferObjects" +
        ".Master")]
    [System.SerializableAttribute()]
    public partial class LocalityDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Locality1Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locality1 {
            get {
                return this.Locality1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Locality1Field, value) != true)) {
                    this.Locality1Field = value;
                    this.RaisePropertyChanged("Locality1");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RetailPOSService.IRetailPOSServiceContract", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IRetailPOSServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetCategories", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetCategoriesResponse")]
        RetailPOS.RetailPOSService.ProductCategoryDTO[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/SaveCategoryDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/SaveCategoryDetailsResponse")]
        bool SaveCategoryDetails(RetailPOS.RetailPOSService.ProductCategoryDTO categoryDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetProductByCategory", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetProductByCategoryResponse")]
        RetailPOS.RetailPOSService.ProductDTO[] GetProductByCategory(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetAllProducts", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetAllProductsResponse")]
        RetailPOS.RetailPOSService.ProductDTO[] GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetCommonProduct", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetCommonProductResponse")]
        RetailPOS.RetailPOSService.ProductDTO[] GetCommonProduct();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetProductStatus", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetProductStatusResponse")]
        RetailPOS.RetailPOSService.ProductStatusDTO[] GetProductStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/SaveProductDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/SaveProductDetailsResponse")]
        bool SaveProductDetails(RetailPOS.RetailPOSService.ProductDTO productDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetStaffDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetStaffDetailsResponse")]
        RetailPOS.RetailPOSService.StaffDTO[] GetStaffDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/ValidateUserCredentials", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/ValidateUserCredentialsResponse")]
        bool ValidateUserCredentials(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetAllCustomers", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetAllCustomersResponse")]
        RetailPOS.RetailPOSService.CustomerDTO[] GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/SaveCustomerDetail", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/SaveCustomerDetailResponse")]
        bool SaveCustomerDetail(RetailPOS.RetailPOSService.CustomerDTO customerDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/UpdateCustomerDetail", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/UpdateCustomerDetailResponse")]
        bool UpdateCustomerDetail(RetailPOS.RetailPOSService.CustomerDTO customerDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetCustomerStatus", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetCustomerStatusResponse")]
        RetailPOS.RetailPOSService.CustomerStatusDTO[] GetCustomerStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetCustomerTypes", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetCustomerTypesResponse")]
        RetailPOS.RetailPOSService.CustomerTypeDTO[] GetCustomerTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/SaveShopSetting", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/SaveShopSettingResponse")]
        bool SaveShopSetting(RetailPOS.RetailPOSService.ShopSettingDTO shopSettingDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetPromotionalOfferDetail", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetPromotionalOfferDetailResponse")]
        RetailPOS.RetailPOSService.PromotionalOfferDTO[] GetPromotionalOfferDetail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/SaveWasteManagement", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/SaveWasteManagementResponse")]
        bool SaveWasteManagement(RetailPOS.RetailPOSService.WasteManagementDTO wasteManagementDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/SavePromotionalOffer", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/SavePromotionalOfferResponse")]
        bool SavePromotionalOffer(RetailPOS.RetailPOSService.PromotionalOfferDTO promotionalOfferDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetCountryDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetCountryDetailsResponse")]
        RetailPOS.RetailPOSService.CountryDTO[] GetCountryDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetTownCityDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetTownCityDetailsResponse")]
        RetailPOS.RetailPOSService.TownCityDTO[] GetTownCityDetails(int countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetLocalityDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetLocalityDetailsResponse")]
        RetailPOS.RetailPOSService.LocalityDTO[] GetLocalityDetails(int townCityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetStreetDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetStreetDetailsResponse")]
        RetailPOS.RetailPOSService.StreetDTO[] GetStreetDetails(int localityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetPostalCodeDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetPostalCodeDetailsResponse")]
        RetailPOS.RetailPOSService.PostCodeDTO[] GetPostalCodeDetails(int localityId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRetailPOSServiceContract/GetMeasureUnitDetails", ReplyAction="http://tempuri.org/IRetailPOSServiceContract/GetMeasureUnitDetailsResponse")]
        RetailPOS.RetailPOSService.MeasureUnitDTO[] GetMeasureUnitDetails();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetailPOSServiceContractChannel : RetailPOS.RetailPOSService.IRetailPOSServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetailPOSServiceContractClient : System.ServiceModel.ClientBase<RetailPOS.RetailPOSService.IRetailPOSServiceContract>, RetailPOS.RetailPOSService.IRetailPOSServiceContract {
        
        public RetailPOSServiceContractClient() {
        }
        
        public RetailPOSServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetailPOSServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailPOSServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetailPOSServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RetailPOS.RetailPOSService.ProductCategoryDTO[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public bool SaveCategoryDetails(RetailPOS.RetailPOSService.ProductCategoryDTO categoryDetails) {
            return base.Channel.SaveCategoryDetails(categoryDetails);
        }
        
        public RetailPOS.RetailPOSService.ProductDTO[] GetProductByCategory(int categoryId) {
            return base.Channel.GetProductByCategory(categoryId);
        }
        
        public RetailPOS.RetailPOSService.ProductDTO[] GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public RetailPOS.RetailPOSService.ProductDTO[] GetCommonProduct() {
            return base.Channel.GetCommonProduct();
        }
        
        public RetailPOS.RetailPOSService.ProductStatusDTO[] GetProductStatus() {
            return base.Channel.GetProductStatus();
        }
        
        public bool SaveProductDetails(RetailPOS.RetailPOSService.ProductDTO productDetails) {
            return base.Channel.SaveProductDetails(productDetails);
        }
        
        public RetailPOS.RetailPOSService.StaffDTO[] GetStaffDetails() {
            return base.Channel.GetStaffDetails();
        }
        
        public bool ValidateUserCredentials(string userName, string password) {
            return base.Channel.ValidateUserCredentials(userName, password);
        }
        
        public RetailPOS.RetailPOSService.CustomerDTO[] GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public bool SaveCustomerDetail(RetailPOS.RetailPOSService.CustomerDTO customerDetails) {
            return base.Channel.SaveCustomerDetail(customerDetails);
        }
        
        public bool UpdateCustomerDetail(RetailPOS.RetailPOSService.CustomerDTO customerDetail) {
            return base.Channel.UpdateCustomerDetail(customerDetail);
        }
        
        public RetailPOS.RetailPOSService.CustomerStatusDTO[] GetCustomerStatus() {
            return base.Channel.GetCustomerStatus();
        }
        
        public RetailPOS.RetailPOSService.CustomerTypeDTO[] GetCustomerTypes() {
            return base.Channel.GetCustomerTypes();
        }
        
        public bool SaveShopSetting(RetailPOS.RetailPOSService.ShopSettingDTO shopSettingDetails) {
            return base.Channel.SaveShopSetting(shopSettingDetails);
        }
        
        public RetailPOS.RetailPOSService.PromotionalOfferDTO[] GetPromotionalOfferDetail() {
            return base.Channel.GetPromotionalOfferDetail();
        }
        
        public bool SaveWasteManagement(RetailPOS.RetailPOSService.WasteManagementDTO wasteManagementDetails) {
            return base.Channel.SaveWasteManagement(wasteManagementDetails);
        }
        
        public bool SavePromotionalOffer(RetailPOS.RetailPOSService.PromotionalOfferDTO promotionalOfferDetails) {
            return base.Channel.SavePromotionalOffer(promotionalOfferDetails);
        }
        
        public RetailPOS.RetailPOSService.CountryDTO[] GetCountryDetails() {
            return base.Channel.GetCountryDetails();
        }
        
        public RetailPOS.RetailPOSService.TownCityDTO[] GetTownCityDetails(int countryId) {
            return base.Channel.GetTownCityDetails(countryId);
        }
        
        public RetailPOS.RetailPOSService.LocalityDTO[] GetLocalityDetails(int townCityId) {
            return base.Channel.GetLocalityDetails(townCityId);
        }
        
        public RetailPOS.RetailPOSService.StreetDTO[] GetStreetDetails(int localityId) {
            return base.Channel.GetStreetDetails(localityId);
        }
        
        public RetailPOS.RetailPOSService.PostCodeDTO[] GetPostalCodeDetails(int localityId) {
            return base.Channel.GetPostalCodeDetails(localityId);
        }
        
        public RetailPOS.RetailPOSService.MeasureUnitDTO[] GetMeasureUnitDetails() {
            return base.Channel.GetMeasureUnitDetails();
        }
    }
}
