//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class customer_pay_card_details : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual long pay_history_id
        {
            get { return _pay_history_id; }
            set
            {
                if (_pay_history_id != value)
                {
                    if (customer_pay_history != null && customer_pay_history.id != value)
                    {
                        customer_pay_history = null;
                    }
                    _pay_history_id = value;
                }
            }
        }
        private long _pay_history_id;

        #endregion
        #region Navigation Properties
    
        public virtual customer_pay_history customer_pay_history
        {
            get { return _customer_pay_history; }
            set
            {
                if (!ReferenceEquals(_customer_pay_history, value))
                {
                    var previousValue = _customer_pay_history;
                    _customer_pay_history = value;
                    Fixupcustomer_pay_history(previousValue);
                }
            }
        }
        private customer_pay_history _customer_pay_history;

        #endregion
        #region Association Fixup
    
        private void Fixupcustomer_pay_history(customer_pay_history previousValue)
        {
            if (previousValue != null && previousValue.customer_pay_card_details.Contains(this))
            {
                previousValue.customer_pay_card_details.Remove(this);
            }
    
            if (customer_pay_history != null)
            {
                if (!customer_pay_history.customer_pay_card_details.Contains(this))
                {
                    customer_pay_history.customer_pay_card_details.Add(this);
                }
                if (pay_history_id != customer_pay_history.id)
                {
                    pay_history_id = customer_pay_history.id;
                }
            }
        }

        #endregion
    }
}
