//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class street : EntityBase
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string street1
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<address> addresses
        {
            get
            {
                if (_addresses == null)
                {
                    var newCollection = new FixupCollection<address>();
                    newCollection.CollectionChanged += Fixupaddresses;
                    _addresses = newCollection;
                }
                return _addresses;
            }
            set
            {
                if (!ReferenceEquals(_addresses, value))
                {
                    var previousValue = _addresses as FixupCollection<address>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupaddresses;
                    }
                    _addresses = value;
                    var newValue = value as FixupCollection<address>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupaddresses;
                    }
                }
            }
        }
        private ICollection<address> _addresses;

        #endregion
        #region Association Fixup
    
        private void Fixupaddresses(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (address item in e.NewItems)
                {
                    item.street = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (address item in e.OldItems)
                {
                    if (ReferenceEquals(item.street, this))
                    {
                        item.street = null;
                    }
                }
            }
        }

        #endregion
    }
}
