//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class account : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual int customer_id
        {
            get { return _customer_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_customer_id != value)
                    {
                        if (customer != null && customer.id != value)
                        {
                            customer = null;
                        }
                        _customer_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _customer_id;
    
        public virtual string gateway
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> date
        {
            get;
            set;
        }
    
        public virtual string description
        {
            get;
            set;
        }
    
        public virtual decimal amount
        {
            get;
            set;
        }
    
        public virtual decimal fees
        {
            get;
            set;
        }
    
        public virtual string transid
        {
            get;
            set;
        }
    
        public virtual Nullable<long> invoice_id
        {
            get { return _invoice_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_invoice_id != value)
                    {
                        if (invoice != null && invoice.id != value)
                        {
                            invoice = null;
                        }
                        _invoice_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _invoice_id;

        #endregion
        #region Navigation Properties
    
        public virtual customer customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    Fixupcustomer(previousValue);
                }
            }
        }
        private customer _customer;
    
        public virtual invoice invoice
        {
            get { return _invoice; }
            set
            {
                if (!ReferenceEquals(_invoice, value))
                {
                    var previousValue = _invoice;
                    _invoice = value;
                    Fixupinvoice(previousValue);
                }
            }
        }
        private invoice _invoice;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupcustomer(customer previousValue)
        {
            if (previousValue != null && previousValue.accounts.Contains(this))
            {
                previousValue.accounts.Remove(this);
            }
    
            if (customer != null)
            {
                if (!customer.accounts.Contains(this))
                {
                    customer.accounts.Add(this);
                }
                if (customer_id != customer.id)
                {
                    customer_id = customer.id;
                }
            }
        }
    
        private void Fixupinvoice(invoice previousValue)
        {
            if (previousValue != null && previousValue.accounts.Contains(this))
            {
                previousValue.accounts.Remove(this);
            }
    
            if (invoice != null)
            {
                if (!invoice.accounts.Contains(this))
                {
                    invoice.accounts.Add(this);
                }
                if (invoice_id != invoice.id)
                {
                    invoice_id = invoice.id;
                }
            }
            else if (!_settingFK)
            {
                invoice_id = null;
            }
        }

        #endregion
    }
}
