//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class address : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual string building_name
        {
            get;
            set;
        }
    
        public virtual string house_no
        {
            get;
            set;
        }
    
        public virtual int street_id
        {
            get;
            set;
        }
    
        public virtual Nullable<long> locality_id
        {
            get;
            set;
        }
    
        public virtual Nullable<short> town_city_id
        {
            get;
            set;
        }
    
        public virtual Nullable<short> country_id
        {
            get;
            set;
        }
    
        public virtual int postcode_id
        {
            get;
            set;
        }

        #endregion
    }
}
