//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class email_templates : EntityBase
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string subject
        {
            get;
            set;
        }
    
        public virtual string from_email
        {
            get;
            set;
        }
    
        public virtual string from_name
        {
            get;
            set;
        }
    
        public virtual string plain_msg
        {
            get;
            set;
        }
    
        public virtual string message
        {
            get;
            set;
        }

        #endregion
    }
}
