//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class general_settings : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string value
        {
            get;
            set;
        }
    
        public virtual string @default
        {
            get;
            set;
        }
    
        public virtual string group
        {
            get;
            set;
        }
    
        public virtual string type
        {
            get;
            set;
        }
    
        public virtual string description
        {
            get;
            set;
        }

        #endregion
    }
}
