//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class invoice : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual int customer_id
        {
            get;
            set;
        }
    
        public virtual string invoicenum
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> date
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> duedate
        {
            get;
            set;
        }
    
        public virtual System.DateTime datepaid
        {
            get;
            set;
        }
    
        public virtual decimal subtotal
        {
            get;
            set;
        }
    
        public virtual decimal credit
        {
            get;
            set;
        }
    
        public virtual decimal tax
        {
            get;
            set;
        }
    
        public virtual decimal tax2
        {
            get;
            set;
        }
    
        public virtual decimal delivery_charge
        {
            get;
            set;
        }
    
        public virtual decimal discount
        {
            get;
            set;
        }
    
        public virtual decimal total
        {
            get;
            set;
        }
    
        public virtual decimal balance
        {
            get;
            set;
        }
    
        public virtual decimal taxrate
        {
            get;
            set;
        }
    
        public virtual decimal taxrate2
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> discount_rate
        {
            get;
            set;
        }
    
        public virtual string promotional_offer_code
        {
            get;
            set;
        }
    
        public virtual string status
        {
            get;
            set;
        }
    
        public virtual string paymentmethod
        {
            get;
            set;
        }
    
        public virtual string notes
        {
            get;
            set;
        }

        #endregion
    }
}
