//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class invoicecredit : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual int customer_id
        {
            get { return _customer_id; }
            set
            {
                if (_customer_id != value)
                {
                    if (customer != null && customer.id != value)
                    {
                        customer = null;
                    }
                    _customer_id = value;
                }
            }
        }
        private int _customer_id;
    
        public virtual System.DateTime date
        {
            get;
            set;
        }
    
        public virtual string description
        {
            get;
            set;
        }
    
        public virtual decimal amount
        {
            get;
            set;
        }
    
        public virtual long relid
        {
            get { return _relid; }
            set
            {
                if (_relid != value)
                {
                    if (invoice != null && invoice.id != value)
                    {
                        invoice = null;
                    }
                    _relid = value;
                }
            }
        }
        private long _relid;

        #endregion
        #region Navigation Properties
    
        public virtual customer customer
        {
            get { return _customer; }
            set
            {
                if (!ReferenceEquals(_customer, value))
                {
                    var previousValue = _customer;
                    _customer = value;
                    Fixupcustomer(previousValue);
                }
            }
        }
        private customer _customer;
    
        public virtual invoice invoice
        {
            get { return _invoice; }
            set
            {
                if (!ReferenceEquals(_invoice, value))
                {
                    var previousValue = _invoice;
                    _invoice = value;
                    Fixupinvoice(previousValue);
                }
            }
        }
        private invoice _invoice;

        #endregion
        #region Association Fixup
    
        private void Fixupcustomer(customer previousValue)
        {
            if (previousValue != null && previousValue.invoicecredits.Contains(this))
            {
                previousValue.invoicecredits.Remove(this);
            }
    
            if (customer != null)
            {
                if (!customer.invoicecredits.Contains(this))
                {
                    customer.invoicecredits.Add(this);
                }
                if (customer_id != customer.id)
                {
                    customer_id = customer.id;
                }
            }
        }
    
        private void Fixupinvoice(invoice previousValue)
        {
            if (previousValue != null && previousValue.invoicecredits.Contains(this))
            {
                previousValue.invoicecredits.Remove(this);
            }
    
            if (invoice != null)
            {
                if (!invoice.invoicecredits.Contains(this))
                {
                    invoice.invoicecredits.Add(this);
                }
                if (relid != invoice.id)
                {
                    relid = invoice.id;
                }
            }
        }

        #endregion
    }
}
