//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class measure_unit_conversion : EntityBase
    {
        #region Primitive Properties
    
        public virtual short from_unit_id
        {
            get;
            set;
        }
    
        public virtual short to_unit_id
        {
            get;
            set;
        }
    
        public virtual decimal conversion_rate
        {
            get;
            set;
        }

        #endregion
    }
}
