//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class product_purchase_history_master : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual System.DateTime purchase_date
        {
            get;
            set;
        }
    
        public virtual Nullable<short> supplier_id
        {
            get;
            set;
        }
    
        public virtual string shop_code
        {
            get;
            set;
        }
    
        public virtual string invoice_no
        {
            get;
            set;
        }
    
        public virtual decimal sub_total
        {
            get;
            set;
        }
    
        public virtual decimal discount
        {
            get;
            set;
        }
    
        public virtual decimal grand_total
        {
            get;
            set;
        }
    
        public virtual decimal cash
        {
            get;
            set;
        }
    
        public virtual decimal credit
        {
            get;
            set;
        }

        #endregion
    }
}
