//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class product_purchase_history_child : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual long history_master_id
        {
            get;
            set;
        }
    
        public virtual short product_id
        {
            get;
            set;
        }
    
        public virtual decimal quantity
        {
            get;
            set;
        }
    
        public virtual short measure_unit_id
        {
            get;
            set;
        }
    
        public virtual decimal rate
        {
            get;
            set;
        }
    
        public virtual string discount_type
        {
            get;
            set;
        }
    
        public virtual decimal raw_discount
        {
            get;
            set;
        }
    
        public virtual decimal discount
        {
            get;
            set;
        }

        #endregion
    }
}
