//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class shop_info : EntityBase
    {
        #region Primitive Properties
    
        public virtual string code
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string phone
        {
            get;
            set;
        }
    
        public virtual string fax
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }
    
        public virtual string website
        {
            get;
            set;
        }
    
        public virtual decimal tax_rate
        {
            get;
            set;
        }
    
        public virtual string currency
        {
            get;
            set;
        }
    
        public virtual Nullable<long> address_id
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ordermaster> ordermasters
        {
            get
            {
                if (_ordermasters == null)
                {
                    var newCollection = new FixupCollection<ordermaster>();
                    newCollection.CollectionChanged += Fixupordermasters;
                    _ordermasters = newCollection;
                }
                return _ordermasters;
            }
            set
            {
                if (!ReferenceEquals(_ordermasters, value))
                {
                    var previousValue = _ordermasters as FixupCollection<ordermaster>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupordermasters;
                    }
                    _ordermasters = value;
                    var newValue = value as FixupCollection<ordermaster>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupordermasters;
                    }
                }
            }
        }
        private ICollection<ordermaster> _ordermasters;
    
        public virtual ICollection<product_purchase_history_master> product_purchase_history_master
        {
            get
            {
                if (_product_purchase_history_master == null)
                {
                    var newCollection = new FixupCollection<product_purchase_history_master>();
                    newCollection.CollectionChanged += Fixupproduct_purchase_history_master;
                    _product_purchase_history_master = newCollection;
                }
                return _product_purchase_history_master;
            }
            set
            {
                if (!ReferenceEquals(_product_purchase_history_master, value))
                {
                    var previousValue = _product_purchase_history_master as FixupCollection<product_purchase_history_master>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupproduct_purchase_history_master;
                    }
                    _product_purchase_history_master = value;
                    var newValue = value as FixupCollection<product_purchase_history_master>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupproduct_purchase_history_master;
                    }
                }
            }
        }
        private ICollection<product_purchase_history_master> _product_purchase_history_master;

        #endregion
        #region Association Fixup
    
        private void Fixupordermasters(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ordermaster item in e.NewItems)
                {
                    item.shop_info = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ordermaster item in e.OldItems)
                {
                    if (ReferenceEquals(item.shop_info, this))
                    {
                        item.shop_info = null;
                    }
                }
            }
        }
    
        private void Fixupproduct_purchase_history_master(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (product_purchase_history_master item in e.NewItems)
                {
                    item.shop_info = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (product_purchase_history_master item in e.OldItems)
                {
                    if (ReferenceEquals(item.shop_info, this))
                    {
                        item.shop_info = null;
                    }
                }
            }
        }

        #endregion
    }
}
