//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class shop_info : EntityBase
    {
        #region Primitive Properties
    
        public virtual string code
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string phone
        {
            get;
            set;
        }
    
        public virtual string fax
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }
    
        public virtual string website
        {
            get;
            set;
        }
    
        public virtual decimal tax_rate
        {
            get;
            set;
        }
    
        public virtual string currency
        {
            get;
            set;
        }
    
        public virtual Nullable<long> address_id
        {
            get;
            set;
        }

        #endregion
    }
}
