//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class staff : EntityBase
    {
        #region Primitive Properties
    
        public virtual short id
        {
            get;
            set;
        }
    
        public virtual string code
        {
            get;
            set;
        }
    
        public virtual string last_name
        {
            get;
            set;
        }
    
        public virtual string first_name
        {
            get;
            set;
        }
    
        public virtual System.DateTime dateofbirth
        {
            get;
            set;
        }
    
        public virtual Nullable<short> designation_id
        {
            get;
            set;
        }
    
        public virtual string phone
        {
            get;
            set;
        }
    
        public virtual string mobile
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }
    
        public virtual string username
        {
            get;
            set;
        }
    
        public virtual System.DateTime hire_date
        {
            get;
            set;
        }
    
        public virtual short status_id
        {
            get;
            set;
        }
    
        public virtual string image_path
        {
            get;
            set;
        }
    
        public virtual Nullable<short> department_id
        {
            get;
            set;
        }
    
        public virtual Nullable<long> address_id
        {
            get;
            set;
        }
    
        public virtual string openid_id
        {
            get;
            set;
        }
    
        public virtual Nullable<short> openid_server_id
        {
            get;
            set;
        }
    
        public virtual string password
        {
            get;
            set;
        }
    
        public virtual Nullable<short> security_group_id
        {
            get;
            set;
        }

        #endregion
    }
}
