//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class supplier : EntityBase
    {
        #region Primitive Properties
    
        public virtual short id
        {
            get;
            set;
        }
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual string phone
        {
            get;
            set;
        }
    
        public virtual string mobile
        {
            get;
            set;
        }
    
        public virtual string email
        {
            get;
            set;
        }
    
        public virtual Nullable<long> address_id
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<product_purchase_history_master> product_purchase_history_master
        {
            get
            {
                if (_product_purchase_history_master == null)
                {
                    var newCollection = new FixupCollection<product_purchase_history_master>();
                    newCollection.CollectionChanged += Fixupproduct_purchase_history_master;
                    _product_purchase_history_master = newCollection;
                }
                return _product_purchase_history_master;
            }
            set
            {
                if (!ReferenceEquals(_product_purchase_history_master, value))
                {
                    var previousValue = _product_purchase_history_master as FixupCollection<product_purchase_history_master>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupproduct_purchase_history_master;
                    }
                    _product_purchase_history_master = value;
                    var newValue = value as FixupCollection<product_purchase_history_master>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupproduct_purchase_history_master;
                    }
                }
            }
        }
        private ICollection<product_purchase_history_master> _product_purchase_history_master;
    
        public virtual ICollection<product> products
        {
            get
            {
                if (_products == null)
                {
                    var newCollection = new FixupCollection<product>();
                    newCollection.CollectionChanged += Fixupproducts;
                    _products = newCollection;
                }
                return _products;
            }
            set
            {
                if (!ReferenceEquals(_products, value))
                {
                    var previousValue = _products as FixupCollection<product>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupproducts;
                    }
                    _products = value;
                    var newValue = value as FixupCollection<product>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupproducts;
                    }
                }
            }
        }
        private ICollection<product> _products;

        #endregion
        #region Association Fixup
    
        private void Fixupproduct_purchase_history_master(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (product_purchase_history_master item in e.NewItems)
                {
                    item.supplier = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (product_purchase_history_master item in e.OldItems)
                {
                    if (ReferenceEquals(item.supplier, this))
                    {
                        item.supplier = null;
                    }
                }
            }
        }
    
        private void Fixupproducts(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (product item in e.NewItems)
                {
                    if (!item.suppliers.Contains(this))
                    {
                        item.suppliers.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (product item in e.OldItems)
                {
                    if (item.suppliers.Contains(this))
                    {
                        item.suppliers.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
