//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class warranty : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual short product_id
        {
            get;
            set;
        }
    
        public virtual string serial_no
        {
            get;
            set;
        }
    
        public virtual System.DateTime start_time
        {
            get;
            set;
        }
    
        public virtual System.DateTime end_time
        {
            get;
            set;
        }

        #endregion
    }
}
