//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class wastemanagement : EntityBase
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual short ProductId
        {
            get { return _productId; }
            set
            {
                if (_productId != value)
                {
                    if (product != null && product.id != value)
                    {
                        product = null;
                    }
                    _productId = value;
                }
            }
        }
        private short _productId;
    
        public virtual decimal Quantity
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Weight
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual product product
        {
            get { return _product; }
            set
            {
                if (!ReferenceEquals(_product, value))
                {
                    var previousValue = _product;
                    _product = value;
                    Fixupproduct(previousValue);
                }
            }
        }
        private product _product;

        #endregion
        #region Association Fixup
    
        private void Fixupproduct(product previousValue)
        {
            if (previousValue != null && previousValue.wastemanagements.Contains(this))
            {
                previousValue.wastemanagements.Remove(this);
            }
    
            if (product != null)
            {
                if (!product.wastemanagements.Contains(this))
                {
                    product.wastemanagements.Add(this);
                }
                if (ProductId != product.id)
                {
                    ProductId = product.id;
                }
            }
        }

        #endregion
    }
}
