//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace RetailPOS.PersistenceLayer.Repository.Entities
{
    public partial class working_record : EntityBase
    {
        #region Primitive Properties
    
        public virtual long id
        {
            get;
            set;
        }
    
        public virtual System.TimeSpan in_time
        {
            get;
            set;
        }
    
        public virtual System.TimeSpan out_time
        {
            get;
            set;
        }
    
        public virtual string total_hours
        {
            get;
            set;
        }
    
        public virtual System.DateTime work_date
        {
            get;
            set;
        }
    
        public virtual short staff_id
        {
            get;
            set;
        }

        #endregion
    }
}
